### ISSUE TITLE
Potential energy in capacitor seems to be wrong

### ISSUE THREAD

**Issue by gabbe-k** [edvinalestig/formelblad_EEM076#2]
(5.1.1)

![image](https://user-images.githubusercontent.com/44163424/119329502-93b95100-bc85-11eb-9bff-71098c445336.png)

Should be this? 

![image](https://user-images.githubusercontent.com/44163424/119329578-a9c71180-bc85-11eb-8770-966857cb7d6c.png)

**Comment by edvinalestig** [comment]
Fixed
